apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-cluster-storage-operator
  name: csi-snapshot-controller-operator-config
  labels:
    app: csi-snapshot-controller-operator
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-production-edge: "true"
data:
  operator-config.yaml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
