# TODO: check if it is needed (and what's missing to get prometheus metrics)
apiVersion: v1
kind: Service
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    service.alpha.openshift.io/serving-cert-secret-name: serving-cert
    include.release.openshift.io/single-node-production-edge: "true"
  labels:
    app: csi-snapshot-controller-operator
  name: csi-snapshot-controller-operator-metrics
  namespace: openshift-cluster-storage-operator
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: csi-snapshot-controller-operator
  sessionAffinity: None
  type: ClusterIP
