kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-snapshot-controller-operator-clusterrole
  annotations:
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
rules:
- apiGroups:
  - operator.openshift.io
  resources:
  - csisnapshotcontrollers
  verbs:
  - "*"
- apiGroups:
  - operator.openshift.io
  resources:
  - csisnapshotcontrollers/status
  verbs:
  - "*"
- apiGroups:
  - config.openshift.io
  resources:
  - clusteroperators
  verbs:
  - "*"
- apiGroups:
  - config.openshift.io
  resources:
  - clusteroperators/status
  verbs:
  - "*"
- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - featuregates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - "*"
